[window]
#dimentions = { columns = 0, lines = 0}
#padding = { x = 10, y = 10}
option_as_alt = "Both"

[scrolling]
#history = 100000

[font]
normal = { family = "MesloLGS Nerd Font Mono" }
size = 12.00


# Default colors
[colors.primary]
background = '#000000'
foreground = '#c7c7c7'

# Normal colors
[colors.normal]
black   = '#333333'
red     = '#c91b00'
green   = '#00c200'
yellow  = '#c7c400'
blue    = '#1a42ff'
magenta = '#c930c7'
cyan    = '#00c5c7'
white   = '#c7c7c7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#ff6d67'
green   = '#5ff967'
yellow  = '#fefb67'
blue    = '#6871ff'
magenta = '#ff76ff'
cyan    = '#5ffdff'
white   = '#fffeff'

#Dim colors
[colors.dim]
#black   = '#ffffff'

